### PR TITLE
Fix QuickTree v1.0.0 to work with Cacti v1.x

### PR DESCRIPTION
**Pull request by netniV**
Fixes a number of issues with QuickTree for Cacti 1.x
- Updated style to make easier identification of what can be done
- Save functionality now works with 1.x
- Header/Footer functionality now use 1.x methods

Known issue:
- Clicking a different tree when using the Save To Branch link
  causes the window to disappear
- No sorting is performed of tree/branch items, this is up to
  the user as it is usually a personal preference

### CODE REVIEW

**Comment by howardjones** [comment]
Aha, nice! I'll give it a try this evening before merging.

**Comment by netniV** [comment]
I like the UI that gets used for the Save To Existing.  I was thinking it should be extended to include the name that gets used (still defaulting to what you had it at) so before you save it, the user has a change to rename it.  The same could also be used for the create new tree part.

Oh and I never checked if the clear function checks if the user really wants to do it, or just clears it.  If you've added a lot of graphs, that could be a pain :)

**Comment by howardjones** [comment]
I used a fresh install, so I don't have any graphs yet to collect (leaving it running overnight). But first comment: 
I'd perhaps make the 3 action options into <BUTTON>s or something similar. Anytime you need to say "(click on the gray headers)", there's a failure in the design to make it clear. It should be obvious what you click on.

**Comment by netniV** [comment]
Yeah, previously they were just inline text, so it wasn't obvious because of the themes. Hence I switched it up a bit as an idea :)

**Comment by netniV** [comment]
Added a fix for sequence, dates and userid's to taken from tree.php.

**Comment by netniV** [comment]
I have now updated the styling to be consistent with the base cacti project.  @cigamit did ponder about whether to bring this plugin into the base system, so you may want to contact him on that point.

**Comment by netniV** [comment]
The plugin is now fully tested and 1.x compatible.  It looks quite a bit different now to the original, but should it ever be brought into the base, it will hopefully need very little work :)

**Comment by jpobeda** [comment]
It works!

**Comment by howardjones** [comment]
merged, and also merged cacti1x-rework back to master... if we're happy, I'll tag it as a new release?

**Comment by netniV** [comment]
Yeah, I think it's ready.  Haven't found any more errors so far.  The one bug that I did get told about turned out to be a base fix in cacti a few versions ago :)

**Pull request merged**
